name: buildandpush

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'uarenforecasting/goes_viewer'
    steps:
      - uses: actions/checkout@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: harbor.x.energy.arizona.edu/library/goes_viewer
          tags: |
            type=semver, pattern={{version}}
            type=ref, event=branch
            type=ref, event=tag
            type=sha

      - name: Log in to registry
        uses: docker/login-action@v1
        with:
          registry: harbor.x.energy.arizona.edu
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{steps.meta.ouputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
